package modelo;
// Generated 29-may-2014 20:28:38 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="tiendaentradas"
    , uniqueConstraints = {@UniqueConstraint(columnNames="nombre"), @UniqueConstraint(columnNames="email")} 
)
public class Admin  implements java.io.Serializable {


     private Integer idAdmin;
     private String nombre;
     private String contrasenia;
     private String email;

    public Admin() {
    }

	
    public Admin(String nombre, String contrasenia) {
        this.nombre = nombre;
        this.contrasenia = contrasenia;
    }
    public Admin(String nombre, String contrasenia, String email) {
       this.nombre = nombre;
       this.contrasenia = contrasenia;
       this.email = email;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_admin", unique=true, nullable=false)
    public Integer getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }
    
    @Column(name="nombre", unique=true, nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="contrasenia", nullable=false, length=45)
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    
    @Column(name="email", unique=true, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


