package modelo;
// Generated 03-jun-2014 19:55:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Concierto generated by hbm2java
 */
public class Concierto  implements java.io.Serializable {


     private Integer idConcierto;
     private String nombreGrupo;
     private String genero;
     private String lugar;
     private Date fecha;
     private Float precio;
     private Integer numEntradas;
     private Set ticketscompradoses = new HashSet(0);

    public Concierto() {
    }

	
    public Concierto(String nombreGrupo, String genero, String lugar, Date fecha) {
        this.nombreGrupo = nombreGrupo;
        this.genero = genero;
        this.lugar = lugar;
        this.fecha = fecha;
    }
    public Concierto(String nombreGrupo, String genero, String lugar, Date fecha, Float precio, Integer numEntradas, Set ticketscompradoses) {
       this.nombreGrupo = nombreGrupo;
       this.genero = genero;
       this.lugar = lugar;
       this.fecha = fecha;
       this.precio = precio;
       this.numEntradas = numEntradas;
       this.ticketscompradoses = ticketscompradoses;
    }
   
    public Integer getIdConcierto() {
        return this.idConcierto;
    }
    
    public void setIdConcierto(Integer idConcierto) {
        this.idConcierto = idConcierto;
    }
    public String getNombreGrupo() {
        return this.nombreGrupo;
    }
    
    public void setNombreGrupo(String nombreGrupo) {
        this.nombreGrupo = nombreGrupo;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Integer getNumEntradas() {
        return this.numEntradas;
    }
    
    public void setNumEntradas(Integer numEntradas) {
        this.numEntradas = numEntradas;
    }
    public Set getTicketscompradoses() {
        return this.ticketscompradoses;
    }
    
    public void setTicketscompradoses(Set ticketscompradoses) {
        this.ticketscompradoses = ticketscompradoses;
    }




}


