package modelo;
// Generated 03-jun-2014 19:55:21 by Hibernate Tools 3.2.1.GA



/**
 * Ticketscomprados generated by hbm2java
 */
public class Ticketscomprados  implements java.io.Serializable {


     private Integer idTickets;
     private Concierto concierto;
     private Usuario usuario;

    public Ticketscomprados() {
    }

    public Ticketscomprados(Concierto concierto, Usuario usuario) {
       this.concierto = concierto;
       this.usuario = usuario;
    }
   
    public Integer getIdTickets() {
        return this.idTickets;
    }
    
    public void setIdTickets(Integer idTickets) {
        this.idTickets = idTickets;
    }
    public Concierto getConcierto() {
        return this.concierto;
    }
    
    public void setConcierto(Concierto concierto) {
        this.concierto = concierto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


